In [1]:
import torch
import torch.nn as nn

In [2]:
# 定义一个全连接层
linear = nn.Linear(5,2)


In [3]:
#1.常数初始化
nn.init.zeros_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [4]:
nn.init.ones_(linear.bias)
print(linear.bias)

Parameter containing:
tensor([1., 1.], requires_grad=True)


In [5]:
nn.init.constant_(linear.weight, 10)
print(linear.weight)

Parameter containing:
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]], requires_grad=True)


In [6]:
#2.秩初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


In [7]:
#3.正态分布初始化
nn.init.normal_(linear.weight, mean=0, std=1)
print(linear.weight)

Parameter containing:
tensor([[ 0.4614, -0.3905,  0.5512,  0.2239,  0.5320],
        [-2.3790, -1.1783,  1.1634,  0.7133, -0.5235]], requires_grad=True)


In [9]:
#4.均匀分布初始化
nn.init.uniform_(linear.weight, a=-3.0, b=3.0)
print(linear.weight)

Parameter containing:
tensor([[ 0.3184, -0.9260, -1.3462,  1.6349, -2.9268],
        [-1.9659,  0.2619,  2.9076, -1.8641,  2.2803]], requires_grad=True)


In [12]:
#5.Xavier初始化
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.1327,  0.5054, -0.7629, -0.5841,  0.6057],
        [ 0.1658,  0.1036,  0.4538, -0.4865, -0.5482]], requires_grad=True)


In [11]:
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.1405,  0.6651, -0.8126, -0.0613,  0.4195],
        [-0.9063,  0.4147,  0.3845,  0.0029,  0.4204]], requires_grad=True)


In [13]:
#6.He初始化
nn.init.kaiming_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.1376,  0.7024, -0.9567, -0.0211,  0.4381],
        [ 0.1283,  1.0115,  0.3057, -0.9193, -0.3842]], requires_grad=True)


In [14]:
nn.init.kaiming_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.2630,  0.3805, -0.6261, -1.5818, -0.0923],
        [-0.2794,  0.7438,  0.6354,  0.4481,  1.2429]], requires_grad=True)


In [15]:
input = torch.randn(1,5,device=torch.device('cpu'))
print(input.device)

cpu
