In [1]:
import torch
import torch.nn as nn

In [2]:
# 输入数据
input = torch.randn(3,2)
print(input)
# 得到预测概率值
pred = torch.sigmoid(input)
print(pred)

tensor([[-0.0691, -0.2458],
        [ 0.5585, -0.7156],
        [ 0.1472, -0.6232]])
tensor([[0.4827, 0.4389],
        [0.6361, 0.3284],
        [0.5367, 0.3491]])


In [3]:
# 目标值
target = torch.tensor([[0,1],[1,0],[0,1]],dtype=torch.float)
print(target)

tensor([[0., 1.],
        [1., 0.],
        [0., 1.]])


In [4]:
# 定义损失函数
loss = nn.BCELoss()
print(loss(pred, target))

tensor(0.6925)
