In [1]:
import torch
import torch.nn as nn

In [2]:
# 1. 目标值为顺序编码的标签
input = torch.randn(6,8)
print(input)

tensor([[ 0.5123,  0.5308,  1.6199, -1.3832, -0.2347, -0.4957, -0.9681,  0.2656],
        [ 0.2931,  0.3003,  0.0735, -0.4666,  1.8005,  0.6712,  1.2587, -2.0971],
        [ 1.4715, -0.5159,  1.0164,  0.5506,  0.5938,  0.3258,  0.5062, -0.6200],
        [-0.6273, -1.3923,  0.6954,  1.0603,  0.4350, -1.2014,  0.6723, -0.3931],
        [ 0.1604, -1.5216,  0.1122, -0.9282, -0.4308, -1.4132,  0.2497,  1.3237],
        [ 1.7713, -3.4116,  1.8507,  1.3785, -0.1739, -2.2163, -0.4044, -0.2080]])


In [3]:
# 目标值，6个数据的类别标签（0~7）
target = torch.tensor([1,0,3,7,5,2])
print(target)

tensor([1, 0, 3, 7, 5, 2])


In [4]:
# 定义损失函数
loss = nn.CrossEntropyLoss()
print(loss(input, target))

tensor(2.3238)


In [5]:
# 2.目标值为一组概率（独热编码）
input = torch.randn(6,8)
print(input)

tensor([[-0.6782, -0.5613,  1.4990, -1.3792, -0.7377,  0.5150, -0.5719,  0.2066],
        [-0.1303, -0.8033, -0.7914,  0.0255, -0.2404, -0.6488, -0.8361,  0.3462],
        [ 0.5283,  0.6484, -0.9076,  0.2489, -0.4903, -0.4862,  0.0659, -0.2030],
        [-0.3451,  0.9432, -0.0673, -0.4808, -1.0106,  0.2651,  0.6184,  1.3615],
        [-0.0414,  1.2216, -1.1611, -1.4236,  0.7718,  0.1171, -0.0903, -0.2267],
        [-1.2639, -1.3177, -0.1361,  0.7890, -0.7138, -0.2748, -0.2218, -0.5223]])


In [6]:
target = torch.randn(6,8).softmax(dim=1)
print(target)

tensor([[0.2028, 0.2780, 0.1019, 0.1117, 0.0631, 0.1253, 0.0336, 0.0836],
        [0.0744, 0.0457, 0.0617, 0.2073, 0.0620, 0.0911, 0.1227, 0.3352],
        [0.1609, 0.2074, 0.1261, 0.0379, 0.0197, 0.0242, 0.1762, 0.2477],
        [0.0293, 0.1727, 0.0699, 0.0850, 0.3751, 0.1939, 0.0319, 0.0421],
        [0.1089, 0.0489, 0.0123, 0.0558, 0.0275, 0.0093, 0.0598, 0.6775],
        [0.1202, 0.3918, 0.0699, 0.0430, 0.1709, 0.0037, 0.1214, 0.0791]])


In [7]:
loss = nn.CrossEntropyLoss()
print(loss(input, target))

tensor(2.3925)
