In [7]:
import torch
import numpy as np
from numpy.conftest import dtype

6.3.1 基本张量创建

（1）按内容创建张量


In [4]:
# 传入一个标量
tensor1 = torch.tensor(10)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor(10)
torch.Size([])
torch.int64


In [5]:
# 传入一个一维数组
tensor2 = torch.tensor([1.0,2,3])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([1., 2., 3.])
torch.Size([3])
torch.float32


In [10]:
# 传入一个二维ndarray
tensor3 = torch.tensor(np.array([[1.0,2,3],[4,5,6]]))
print(tensor3)
print(tensor3.size())
print(tensor3.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.Size([2, 3])
torch.float64


(2)创建指定形状的张量

In [13]:
tensor1 = torch.Tensor(3,2,4)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([[[-1.8476e-12,  9.0384e-43,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([3, 2, 4])
torch.float32


In [14]:
tensor2 = torch.Tensor([[1,2,3,4],[4,5,6,7]])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.Size([2, 4])
torch.float32


In [15]:
tensor1 = torch.Tensor(10)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])
torch.float32


(3)创建指定类型的张量

In [17]:
# int(int32)类型
tensor1 = torch.IntTensor([2,3])
tensor2 = torch.tensor([1,2,3], dtype=torch.int32)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int32
torch.int32


In [18]:
#long (int64)类型
tensor1 = torch.LongTensor([2,3])
tensor2 = torch.LongTensor([1,2,3], dtype=torch.int64)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int64
torch.int64


6.3.2 指定区间的张量创建

In [19]:
tensor1 = torch.arange(10,30,2)
print(tensor1)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])


In [20]:
tensor2 = torch.arange(6)
print(tensor2)

tensor([0, 1, 2, 3, 4, 5])


In [21]:
tensor3 = torch.linspace(10,30,6)
print(tensor3)

tensor([10., 14., 18., 22., 26., 30.])


In [22]:
tensor1 = torch.logspace(1,3,3,base=2)
print(tensor1)

tensor([2., 4., 8.])


6.3.3按数值填充张量

In [23]:
tensor1 = torch.zeros(2,3)
print(tensor1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [24]:
tensor2 = torch.ones_like(tensor1)
print(tensor2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [25]:
tensor1 = torch.full((3,2),6.5)
print(tensor1)
print(tensor1.dtype)

tensor([[6.5000, 6.5000],
        [6.5000, 6.5000],
        [6.5000, 6.5000]])
torch.float32


In [26]:
tensor1 = torch.eye(3)
print(tensor1)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [27]:
tensor2 = torch.empty_like(tensor1)
print(tensor2)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [28]:
tensor1 = torch.eye(3,5)
print(tensor1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


6.3.4随机张量创建

In [30]:
tensor1 = torch.rand(2,3)
print(tensor1)

tensor([[0.1936, 0.2608, 0.7869],
        [0.5273, 0.5270, 0.0782]])


In [31]:
tensor2 = torch.rand_like(tensor1)
print(tensor2)

tensor([[0.5183, 0.7874, 0.6052],
        [0.2811, 0.6922, 0.4552]])


In [33]:
tensor1 = torch.randint(low=0,high=100,size=(2,3))
print(tensor1)

tensor([[43, 70, 84],
        [94, 32, 62]])


In [36]:
tensor2 = torch.randint_like(tensor1,low=10,high=50)
print(tensor2)

tensor([[43, 47, 22],
        [15, 49, 29]])


In [37]:
tensor1 = torch.randn(4,2)
print(tensor1)

tensor([[-0.4407,  0.3992],
        [ 0.4151, -1.5282],
        [ 0.5377, -1.7679],
        [ 0.2078, -0.4718]])


In [38]:
tensor2 = torch.randn_like(tensor1)
print(tensor2)

tensor([[ 1.2674,  0.5357],
        [ 1.9451,  2.7897],
        [-0.9654,  0.6289],
        [ 2.4300,  0.0645]])


In [39]:
tensor1 = torch.normal(5,2,tensor2.shape)
print(tensor1)

tensor([[2.1412, 6.2789],
        [4.1151, 5.0205],
        [3.4180, 3.5241],
        [7.8427, 4.4640]])


In [40]:
#随机重新排列
tensor1 = torch.randperm(10)
print(tensor1)

tensor([5, 9, 8, 7, 1, 4, 6, 3, 0, 2])


In [43]:
#查看和指定随机数种子
print(torch.random.initial_seed())

530506887400
