In [1]:
import torch
import numpy as np

In [3]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1)
print(tensor1.dtype)

tensor([1, 2, 3])
torch.int64


In [5]:
tensor1 = tensor1.type(torch.float64)
print(tensor1.dtype)

torch.float64


In [6]:
tensor1 = tensor1.half()
print(tensor1.dtype)

torch.float16


In [7]:
print(tensor1)

tensor([1., 2., 3.], dtype=torch.float16)


In [8]:
tensor1 = tensor1.to(torch.complex64)
print(tensor1,tensor1.dtype)

tensor([1.+0.j, 2.+0.j, 3.+0.j]) torch.complex64


6.4.2Tensor与ndarray转换

In [9]:
np.set_printoptions(precision=6)
torch.set_printoptions(precision=6)

#1. tensor → ndarray
tensor1 = torch.rand(3,2)
print(tensor1)

tensor([[0.268422, 0.636172],
        [0.061928, 0.047677],
        [0.788978, 0.839853]])


In [14]:
ndarray1 =tensor1.numpy()
print(ndarray1)

[[0.268422 0.636172]
 [0.061928 0.047677]
 [0.788978 0.839853]]


In [17]:
tensor1[:, 0] = 10
print(tensor1)
print(ndarray1)

tensor([[10.000000,  0.636172],
        [10.000000,  0.047677],
        [10.000000,  0.839853]])
[[10.        0.636172]
 [10.        0.047677]
 [10.        0.839853]]


In [16]:
# 使用copy方法避免共享内存
ndarray2 = tensor1.numpy().copy()
print(ndarray2)

[[10.        0.636172]
 [10.        0.047677]
 [10.        0.839853]]


In [18]:
tensor1[:, 0] = 5
print(tensor1)
print(ndarray1)
print(ndarray2)

tensor([[5.000000, 0.636172],
        [5.000000, 0.047677],
        [5.000000, 0.839853]])
[[5.       0.636172]
 [5.       0.047677]
 [5.       0.839853]]
[[10.        0.636172]
 [10.        0.047677]
 [10.        0.839853]]


In [19]:
#2.ndarray → tensor
ndarray1 = np.random.randn(3,2)
tensor1 = torch.from_numpy(ndarray1)
print(tensor1)
print(ndarray1)

tensor([[-0.165407, -0.397431],
        [-0.291761, -1.612272],
        [ 1.228428, -0.744045]], dtype=torch.float64)
[[-0.165407 -0.397431]
 [-0.291761 -1.612272]
 [ 1.228428 -0.744045]]


In [20]:
ndarray1[:,0] = 5
print(tensor1)
print(ndarray1)

tensor([[ 5.000000, -0.397431],
        [ 5.000000, -1.612272],
        [ 5.000000, -0.744045]], dtype=torch.float64)
[[ 5.       -0.397431]
 [ 5.       -1.612272]
 [ 5.       -0.744045]]


In [21]:
#使用copy方法避免内存共享
tensor2 = torch.from_numpy(ndarray1.copy())
ndarray1[:,0] = 7
print(ndarray1)
print(tensor1)
print(tensor2)

[[ 7.       -0.397431]
 [ 7.       -1.612272]
 [ 7.       -0.744045]]
tensor([[ 7.000000, -0.397431],
        [ 7.000000, -1.612272],
        [ 7.000000, -0.744045]], dtype=torch.float64)
tensor([[ 5.000000, -0.397431],
        [ 5.000000, -1.612272],
        [ 5.000000, -0.744045]], dtype=torch.float64)


In [22]:
#使用tensor方法直接转换成Tensor
ndarray1 = np.random.randn(3,2)
tensor1 = torch.tensor(ndarray1)
print(tensor1)
print(ndarray1)

tensor([[ 1.044981, -0.662519],
        [ 0.637965, -0.512655],
        [ 0.637125, -0.084013]], dtype=torch.float64)
[[ 1.044981 -0.662519]
 [ 0.637965 -0.512655]
 [ 0.637125 -0.084013]]


In [23]:
ndarray1[:,0] = 5
print(tensor1)
print(ndarray1)

tensor([[ 1.044981, -0.662519],
        [ 0.637965, -0.512655],
        [ 0.637125, -0.084013]], dtype=torch.float64)
[[ 5.       -0.662519]
 [ 5.       -0.512655]
 [ 5.       -0.084013]]


In [24]:
#张量与标量转换
tensor1 = torch.tensor(10)
print(tensor1)

tensor(10)


In [25]:
print(tensor1.item())

10


In [26]:
tensor1 = torch.tensor([[10]])
print(tensor1)
print(tensor1.item())

tensor([[10]])
10
