In [1]:
import torch

In [2]:
# 1.四则运算
tensor1 = torch.randint(low=0, high=10, size=(2, 3))
print(tensor1)

tensor([[5, 9, 9],
        [7, 3, 1]])


In [3]:
print(tensor1 + 10)

tensor([[15, 19, 19],
        [17, 13, 11]])


In [4]:
print(tensor1.add(10))

tensor([[15, 19, 19],
        [17, 13, 11]])


In [5]:
print(tensor1)

tensor([[5, 9, 9],
        [7, 3, 1]])


In [6]:
print(tensor1.add_(10))
print(tensor1)

tensor([[15, 19, 19],
        [17, 13, 11]])
tensor([[15, 19, 19],
        [17, 13, 11]])


In [7]:
print(tensor1.sub_(10))

tensor([[5, 9, 9],
        [7, 3, 1]])


In [8]:
# 幂函数
print(tensor1 ** 2)

tensor([[25, 81, 81],
        [49,  9,  1]])


In [10]:
print(tensor1.pow(2))
print(tensor1)

tensor([[25, 81, 81],
        [49,  9,  1]])
tensor([[5, 9, 9],
        [7, 3, 1]])


In [11]:
print(tensor1.pow_(2))
print(tensor1)

tensor([[25, 81, 81],
        [49,  9,  1]])
tensor([[25, 81, 81],
        [49,  9,  1]])


In [12]:
print(tensor1.sqrt())

tensor([[5., 9., 9.],
        [7., 3., 1.]])


In [13]:
print(tensor1)

tensor([[25, 81, 81],
        [49,  9,  1]])


In [14]:
tensor1 = tensor1.float()
print(tensor1.sqrt_())
print(tensor1)


tensor([[5., 9., 9.],
        [7., 3., 1.]])
tensor([[5., 9., 9.],
        [7., 3., 1.]])


In [15]:
tensor1 = torch.tensor([1.0,2,3])
print(tensor1)
print(2.7182818 ** tensor1)

tensor([1., 2., 3.])
tensor([ 2.7183,  7.3891, 20.0855])


In [16]:
print(tensor1.exp())

tensor([ 2.7183,  7.3891, 20.0855])


In [17]:
print(tensor1)
print(tensor1.exp_())
print(tensor1)

tensor([1., 2., 3.])
tensor([ 2.7183,  7.3891, 20.0855])
tensor([ 2.7183,  7.3891, 20.0855])


In [19]:
#计算张量的哈达玛积
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[1,2],[3,4]])
print(tensor1 + tensor2)
print(tensor1 - tensor2)
print(tensor1 * tensor2)

tensor([[2, 4],
        [6, 8]])
tensor([[0, 0],
        [0, 0]])
tensor([[ 1,  4],
        [ 9, 16]])


In [20]:
print(tensor1.mul(tensor2))

tensor([[ 1,  4],
        [ 9, 16]])


In [21]:
#张量乘法
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2 = torch.tensor([[1,2],[3,4],[5,6]])
print(tensor1 @ tensor2)

tensor([[22, 28],
        [49, 64]])


In [22]:
print(tensor1.matmul(tensor2))

tensor([[22, 28],
        [49, 64]])


In [23]:
print(tensor1.mm(tensor2))

tensor([[22, 28],
        [49, 64]])


In [25]:
tensor1 = torch.tensor([[[1,2,3],[4,5,6]],[[6,5,4],[3,2,1]]])
tensor2 = torch.tensor([[[1,2],[3,4],[5,6]],[[6,5],[4,3],[2,1]]])
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))

tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])
tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])


In [27]:
# print(tensor1.mm(tensor2))
tensor1 = torch.randn(4,2,2,3)
tensor2 = torch.randn(1,1,3,5)
tensor3 = tensor1 @ tensor2
print(tensor3.shape)

torch.Size([4, 2, 2, 5])


In [28]:
# 验证内存的共享和节省内存
X = torch.randint(1,10,(3,2,4))
print(X)
print(id(X))

tensor([[[2, 5, 6, 9],
         [5, 7, 4, 7]],

        [[9, 4, 9, 8],
         [9, 9, 9, 3]],

        [[3, 3, 9, 2],
         [7, 5, 9, 2]]])
1362819485680


In [33]:
# X = X + 10
X += 10
print(X)
print(id(X))

tensor([[[52, 55, 56, 59],
         [55, 57, 54, 57]],

        [[59, 54, 59, 58],
         [59, 59, 59, 53]],

        [[53, 53, 59, 52],
         [57, 55, 59, 52]]])
1362826498992


In [34]:
X = torch.randint(1,10,(3,2,4))
Y = torch.randint(1,10,(3,4,1))
print(X.shape)
print(id(X))
print(X)
print(Y)
print(X @ Y)
X[:] = X @ Y
print(X.shape)
print(X)
print(id(X))

torch.Size([3, 2, 4])
1362826501792
tensor([[[5, 7, 3, 1],
         [7, 8, 2, 5]],

        [[6, 8, 2, 8],
         [2, 9, 6, 6]],

        [[8, 7, 8, 7],
         [1, 6, 5, 4]]])
tensor([[[5],
         [9],
         [1],
         [7]],

        [[6],
         [4],
         [9],
         [4]],

        [[2],
         [8],
         [7],
         [6]]])
tensor([[[ 98],
         [144]],

        [[118],
         [126]],

        [[170],
         [109]]])
torch.Size([3, 2, 4])
tensor([[[ 98,  98,  98,  98],
         [144, 144, 144, 144]],

        [[118, 118, 118, 118],
         [126, 126, 126, 126]],

        [[170, 170, 170, 170],
         [109, 109, 109, 109]]])
1362826501792
