In [1]:
import torch

In [2]:
tensor1 = torch.randint(1,10,(3,2,4)).float()
print(tensor1)

tensor([[[5., 3., 7., 3.],
         [4., 4., 7., 8.]],

        [[9., 1., 9., 6.],
         [6., 1., 8., 3.]],

        [[4., 5., 6., 1.],
         [7., 2., 4., 7.]]])


In [3]:
# sum求和
print(tensor1.sum())

tensor(120.)


In [7]:
print(tensor1.sum(dim=2))

tensor([[18., 23.],
        [25., 18.],
        [16., 20.]])


In [8]:
# mean 求均值
print(tensor1.mean())

tensor(5.)


In [9]:
print(tensor1.mean(dim=2))

tensor([[4.5000, 5.7500],
        [6.2500, 4.5000],
        [4.0000, 5.0000]])


In [10]:
#std 标准方差
print(tensor1.std())

tensor(2.4847)


In [11]:
print(tensor1.std(dim=2))

tensor([[1.9149, 2.0616],
        [3.7749, 3.1091],
        [2.1602, 2.4495]])


In [12]:
#max min求最大最小值
print(tensor1.max())
print(tensor1.max(dim=2))

tensor(9.)
torch.return_types.max(
values=tensor([[7., 8.],
        [9., 8.],
        [6., 7.]]),
indices=tensor([[2, 3],
        [0, 2],
        [2, 0]]))


In [13]:
print(tensor1.min(dim=2))

torch.return_types.min(
values=tensor([[3., 4.],
        [1., 1.],
        [1., 2.]]),
indices=tensor([[1, 0],
        [1, 1],
        [3, 1]]))


In [15]:
print(tensor1.argmax())
print(tensor1.argmax(dim=2))

tensor(8)
tensor([[2, 3],
        [0, 2],
        [2, 0]])


In [16]:
# 去重
print(tensor1.unique())

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [17]:
# 排序
print(tensor1.sort())

torch.return_types.sort(
values=tensor([[[3., 3., 5., 7.],
         [4., 4., 7., 8.]],

        [[1., 6., 9., 9.],
         [1., 3., 6., 8.]],

        [[1., 4., 5., 6.],
         [2., 4., 7., 7.]]]),
indices=tensor([[[1, 3, 0, 2],
         [0, 1, 2, 3]],

        [[1, 3, 0, 2],
         [1, 3, 0, 2]],

        [[3, 0, 1, 2],
         [1, 2, 0, 3]]]))
