In [1]:
import torch

In [2]:
tensor1 = torch.randint(1,10,(3,5,4))
print(tensor1)

tensor([[[5, 6, 9, 9],
         [8, 8, 3, 9],
         [5, 4, 5, 4],
         [2, 8, 5, 4],
         [1, 1, 6, 3]],

        [[2, 5, 5, 7],
         [7, 6, 7, 7],
         [4, 2, 1, 3],
         [1, 4, 4, 2],
         [7, 9, 4, 5]],

        [[7, 7, 1, 7],
         [2, 2, 9, 8],
         [7, 1, 1, 5],
         [7, 9, 5, 5],
         [5, 7, 3, 1]]])


In [3]:
# 1.简单索引
print(tensor1[2,1,3])

tensor(8)


In [4]:
print(tensor1[1])

tensor([[2, 5, 5, 7],
        [7, 6, 7, 7],
        [4, 2, 1, 3],
        [1, 4, 4, 2],
        [7, 9, 4, 5]])


In [5]:
print(tensor1[:,3])

tensor([[2, 8, 5, 4],
        [1, 4, 4, 2],
        [7, 9, 5, 5]])


In [6]:
# 2.索引范围
print(tensor1[1:])

tensor([[[2, 5, 5, 7],
         [7, 6, 7, 7],
         [4, 2, 1, 3],
         [1, 4, 4, 2],
         [7, 9, 4, 5]],

        [[7, 7, 1, 7],
         [2, 2, 9, 8],
         [7, 1, 1, 5],
         [7, 9, 5, 5],
         [5, 7, 3, 1]]])


In [7]:
print(tensor1[-1:,1:4,0:3])

tensor([[[2, 2, 9],
         [7, 1, 1],
         [7, 9, 5]]])


In [8]:
print(tensor1[-1:,1:4:2,0:3:2])

tensor([[[2, 9],
         [7, 5]]])


In [10]:
print(tensor1[-1:,-4:-1:2,0:3:2])

tensor([[[2, 9],
         [7, 5]]])


In [11]:
# 3.列表索引
print(tensor1[[0,1],[3,2]])

tensor([[2, 8, 5, 4],
        [4, 2, 1, 3]])


In [12]:
print(tensor1[[0,1],[3,2],[2,3]])

tensor([5, 3])


In [15]:
print(tensor1[[[0],[1]],[1,2]])

tensor([[[8, 8, 3, 9],
         [5, 4, 5, 4]],

        [[7, 6, 7, 7],
         [4, 2, 1, 3]]])


In [16]:
# 4.布尔索引
# 4.1 选取符合条件的行：首元素大于5
mask = tensor1[:,:,0] > 5
print(mask)

tensor([[False,  True, False, False, False],
        [False,  True, False, False,  True],
        [ True, False,  True,  True, False]])


In [17]:
print(tensor1[mask])

tensor([[8, 8, 3, 9],
        [7, 6, 7, 7],
        [7, 9, 4, 5],
        [7, 7, 1, 7],
        [7, 1, 1, 5],
        [7, 9, 5, 5]])


In [18]:
#4.2 选取符合条件的列：第二个元素大于5
mask = tensor1[:,1,:] > 5
print(mask)

tensor([[ True,  True, False,  True],
        [ True,  True,  True,  True],
        [False, False,  True,  True]])


In [19]:
tensor2 = tensor1.mT
print(tensor2)

tensor([[[5, 8, 5, 2, 1],
         [6, 8, 4, 8, 1],
         [9, 3, 5, 5, 6],
         [9, 9, 4, 4, 3]],

        [[2, 7, 4, 1, 7],
         [5, 6, 2, 4, 9],
         [5, 7, 1, 4, 4],
         [7, 7, 3, 2, 5]],

        [[7, 2, 7, 7, 5],
         [7, 2, 1, 9, 7],
         [1, 9, 1, 5, 3],
         [7, 8, 5, 5, 1]]])


In [20]:
#将mask应用到tensor2上，形状匹配前两个维度
print(tensor2[mask].mT)

tensor([[5, 6, 9, 2, 5, 5, 7, 1, 7],
        [8, 8, 9, 7, 6, 7, 7, 9, 8],
        [5, 4, 4, 4, 2, 1, 3, 1, 5],
        [2, 8, 4, 1, 4, 4, 2, 5, 5],
        [1, 1, 3, 7, 9, 4, 5, 3, 1]])


In [21]:
# 4.3 选取符合条件的矩阵：元素（1，2）> 5
mask = tensor1[:,1,2] > 5
print(mask)

tensor([False,  True,  True])


In [22]:
print(tensor1[mask])

tensor([[[2, 5, 5, 7],
         [7, 6, 7, 7],
         [4, 2, 1, 3],
         [1, 4, 4, 2],
         [7, 9, 4, 5]],

        [[7, 7, 1, 7],
         [2, 2, 9, 8],
         [7, 1, 1, 5],
         [7, 9, 5, 5],
         [5, 7, 3, 1]]])


In [23]:
mask = tensor1 > 5
print(mask)

tensor([[[False,  True,  True,  True],
         [ True,  True, False,  True],
         [False, False, False, False],
         [False,  True, False, False],
         [False, False,  True, False]],

        [[False, False, False,  True],
         [ True,  True,  True,  True],
         [False, False, False, False],
         [False, False, False, False],
         [ True,  True, False, False]],

        [[ True,  True, False,  True],
         [False, False,  True,  True],
         [ True, False, False, False],
         [ True,  True, False, False],
         [False,  True, False, False]]])


In [24]:
print(tensor1[mask])

tensor([6, 9, 9, 8, 8, 9, 8, 6, 7, 7, 6, 7, 7, 7, 9, 7, 7, 7, 9, 8, 7, 7, 9, 7])
