In [1]:
import torch

In [2]:
tensor1 = torch.randint(1,10,(2,3,6))
print(tensor1)

tensor([[[1, 9, 4, 4, 2, 6],
         [3, 8, 4, 7, 1, 2],
         [9, 4, 1, 3, 6, 4]],

        [[2, 7, 7, 3, 5, 4],
         [4, 1, 1, 4, 6, 9],
         [7, 6, 9, 3, 1, 3]]])


6.8.1 交换维度

In [3]:
# 1.交换维度
print(tensor1.transpose(0,2))

tensor([[[1, 2],
         [3, 4],
         [9, 7]],

        [[9, 7],
         [8, 1],
         [4, 6]],

        [[4, 7],
         [4, 1],
         [1, 9]],

        [[4, 3],
         [7, 4],
         [3, 3]],

        [[2, 5],
         [1, 6],
         [6, 1]],

        [[6, 4],
         [2, 9],
         [4, 3]]])


In [4]:
# 2.重新排列多个维度
print(tensor1.permute(0,2,1))

tensor([[[1, 3, 9],
         [9, 8, 4],
         [4, 4, 1],
         [4, 7, 3],
         [2, 1, 6],
         [6, 2, 4]],

        [[2, 4, 7],
         [7, 1, 6],
         [7, 1, 9],
         [3, 4, 3],
         [5, 6, 1],
         [4, 9, 3]]])


6.8.2 调整形状

In [5]:
# 1. reshape
tensor1 = torch.randint(1,10,(3,5,4))
print(tensor1)
print(tensor1.shape)

tensor([[[3, 2, 6, 2],
         [5, 7, 4, 7],
         [1, 6, 4, 8],
         [6, 8, 9, 7],
         [3, 3, 5, 8]],

        [[1, 9, 9, 8],
         [2, 5, 2, 8],
         [9, 8, 1, 6],
         [8, 6, 2, 5],
         [1, 1, 7, 5]],

        [[5, 3, 2, 8],
         [2, 9, 8, 8],
         [2, 3, 9, 3],
         [4, 3, 2, 8],
         [8, 9, 7, 5]]])
torch.Size([3, 5, 4])


In [6]:
print(tensor1.reshape(6,10))

tensor([[3, 2, 6, 2, 5, 7, 4, 7, 1, 6],
        [4, 8, 6, 8, 9, 7, 3, 3, 5, 8],
        [1, 9, 9, 8, 2, 5, 2, 8, 9, 8],
        [1, 6, 8, 6, 2, 5, 1, 1, 7, 5],
        [5, 3, 2, 8, 2, 9, 8, 8, 2, 3],
        [9, 3, 4, 3, 2, 8, 8, 9, 7, 5]])


In [7]:
print(tensor1.reshape(3,-1))

tensor([[3, 2, 6, 2, 5, 7, 4, 7, 1, 6, 4, 8, 6, 8, 9, 7, 3, 3, 5, 8],
        [1, 9, 9, 8, 2, 5, 2, 8, 9, 8, 1, 6, 8, 6, 2, 5, 1, 1, 7, 5],
        [5, 3, 2, 8, 2, 9, 8, 8, 2, 3, 9, 3, 4, 3, 2, 8, 8, 9, 7, 5]])


In [8]:
print(tensor1.reshape(-1))

tensor([3, 2, 6, 2, 5, 7, 4, 7, 1, 6, 4, 8, 6, 8, 9, 7, 3, 3, 5, 8, 1, 9, 9, 8,
        2, 5, 2, 8, 9, 8, 1, 6, 8, 6, 2, 5, 1, 1, 7, 5, 5, 3, 2, 8, 2, 9, 8, 8,
        2, 3, 9, 3, 4, 3, 2, 8, 8, 9, 7, 5])


In [9]:
# 2.view
print(tensor1.is_contiguous())

True


In [10]:
print(tensor1.view(-1,10))


tensor([[3, 2, 6, 2, 5, 7, 4, 7, 1, 6],
        [4, 8, 6, 8, 9, 7, 3, 3, 5, 8],
        [1, 9, 9, 8, 2, 5, 2, 8, 9, 8],
        [1, 6, 8, 6, 2, 5, 1, 1, 7, 5],
        [5, 3, 2, 8, 2, 9, 8, 8, 2, 3],
        [9, 3, 4, 3, 2, 8, 8, 9, 7, 5]])


In [12]:
print(tensor1.shape)

torch.Size([3, 5, 4])


In [14]:
# 对张量进行转置操作，让内存空间不连续
tensor1 = tensor1.permute(2,1,0)
print(tensor1.shape)

torch.Size([5, 4, 3])


In [15]:
print(tensor1.is_contiguous())

False


In [16]:
print(tensor1.contiguous().view(-1,10))

tensor([[3, 1, 5, 2, 9, 3, 6, 9, 2, 2],
        [8, 8, 5, 2, 2, 7, 5, 9, 4, 2],
        [8, 7, 8, 8, 1, 9, 2, 6, 8, 3],
        [4, 1, 9, 8, 6, 3, 6, 8, 4, 8],
        [6, 3, 9, 2, 2, 7, 5, 8, 3, 1],
        [8, 3, 1, 9, 5, 7, 7, 8, 5, 5]])


6.8.3 增加或删除维度

In [17]:
# 1.增加维度
tensor1 = torch.tensor([1,2,3])
print(tensor1)

tensor([1, 2, 3])


In [18]:
# 在0维上增加一个维度，1*3
print(tensor1.unsqueeze(dim=0))

tensor([[1, 2, 3]])


In [20]:
# 在1维上增加一个维度，3*1
print(tensor1.unsqueeze(dim=1))
print(tensor1)

tensor([[1],
        [2],
        [3]])
tensor([1, 2, 3])


In [21]:
print(tensor1.unsqueeze_(dim=-2))
print(tensor1)

tensor([[1, 2, 3]])
tensor([[1, 2, 3]])


In [22]:
# 减少维度
print(tensor1.squeeze(dim=0))
print(tensor1)

tensor([1, 2, 3])
tensor([[1, 2, 3]])


6.9 张量拼接操作

In [24]:
# 1.拼接
tensor1 = torch.randint(1,10,(2,2,5))
tensor2 = torch.randint(1,10,(2,3,5))
print(tensor1)
print(tensor2)

tensor([[[8, 1, 7, 7, 3],
         [3, 9, 5, 8, 8]],

        [[1, 5, 3, 1, 2],
         [8, 4, 9, 6, 6]]])
tensor([[[2, 6, 4, 3, 3],
         [9, 5, 7, 1, 2],
         [7, 6, 1, 5, 4]],

        [[4, 6, 4, 5, 5],
         [2, 2, 1, 6, 1],
         [5, 5, 8, 4, 6]]])


In [25]:
print(torch.cat((tensor1,tensor2),dim=1))

tensor([[[8, 1, 7, 7, 3],
         [3, 9, 5, 8, 8],
         [2, 6, 4, 3, 3],
         [9, 5, 7, 1, 2],
         [7, 6, 1, 5, 4]],

        [[1, 5, 3, 1, 2],
         [8, 4, 9, 6, 6],
         [4, 6, 4, 5, 5],
         [2, 2, 1, 6, 1],
         [5, 5, 8, 4, 6]]])


In [26]:
# 2. 堆叠
tensor1 = torch.randint(1,10,(4,3,5))
tensor2 = torch.randint(1,10,(4,3,5))
print(tensor1)
print(tensor2)

tensor([[[7, 9, 5, 3, 8],
         [6, 7, 2, 8, 7],
         [7, 4, 6, 9, 7]],

        [[4, 1, 3, 1, 5],
         [1, 8, 7, 7, 5],
         [4, 2, 5, 2, 2]],

        [[2, 9, 9, 2, 6],
         [9, 1, 9, 6, 6],
         [6, 3, 4, 1, 5]],

        [[2, 6, 9, 5, 1],
         [3, 3, 8, 6, 2],
         [1, 8, 5, 2, 9]]])
tensor([[[7, 5, 9, 2, 9],
         [5, 3, 4, 9, 5],
         [3, 8, 4, 6, 8]],

        [[6, 6, 7, 2, 4],
         [6, 3, 9, 9, 1],
         [4, 2, 2, 3, 3]],

        [[3, 2, 5, 1, 9],
         [9, 5, 7, 8, 6],
         [9, 6, 2, 5, 4]],

        [[6, 4, 1, 3, 1],
         [1, 7, 6, 5, 8],
         [6, 6, 8, 7, 4]]])


In [27]:
tensor3 = torch.stack([tensor1,tensor2],dim=0)
print(tensor3)
print(tensor3.shape)

tensor([[[[7, 9, 5, 3, 8],
          [6, 7, 2, 8, 7],
          [7, 4, 6, 9, 7]],

         [[4, 1, 3, 1, 5],
          [1, 8, 7, 7, 5],
          [4, 2, 5, 2, 2]],

         [[2, 9, 9, 2, 6],
          [9, 1, 9, 6, 6],
          [6, 3, 4, 1, 5]],

         [[2, 6, 9, 5, 1],
          [3, 3, 8, 6, 2],
          [1, 8, 5, 2, 9]]],


        [[[7, 5, 9, 2, 9],
          [5, 3, 4, 9, 5],
          [3, 8, 4, 6, 8]],

         [[6, 6, 7, 2, 4],
          [6, 3, 9, 9, 1],
          [4, 2, 2, 3, 3]],

         [[3, 2, 5, 1, 9],
          [9, 5, 7, 8, 6],
          [9, 6, 2, 5, 4]],

         [[6, 4, 1, 3, 1],
          [1, 7, 6, 5, 8],
          [6, 6, 8, 7, 4]]]])
torch.Size([2, 4, 3, 5])


In [28]:
tensor3 = torch.stack([tensor1,tensor2],dim=3)
print(tensor3)
print(tensor3.shape)

tensor([[[[7, 7],
          [9, 5],
          [5, 9],
          [3, 2],
          [8, 9]],

         [[6, 5],
          [7, 3],
          [2, 4],
          [8, 9],
          [7, 5]],

         [[7, 3],
          [4, 8],
          [6, 4],
          [9, 6],
          [7, 8]]],


        [[[4, 6],
          [1, 6],
          [3, 7],
          [1, 2],
          [5, 4]],

         [[1, 6],
          [8, 3],
          [7, 9],
          [7, 9],
          [5, 1]],

         [[4, 4],
          [2, 2],
          [5, 2],
          [2, 3],
          [2, 3]]],


        [[[2, 3],
          [9, 2],
          [9, 5],
          [2, 1],
          [6, 9]],

         [[9, 9],
          [1, 5],
          [9, 7],
          [6, 8],
          [6, 6]],

         [[6, 9],
          [3, 6],
          [4, 2],
          [1, 5],
          [5, 4]]],


        [[[2, 6],
          [6, 4],
          [9, 1],
          [5, 3],
          [1, 1]],

         [[3, 1],
          [3, 7],
          [8, 6],
          [6, 5],
  