In [2]:
import torch

In [3]:
# 定义数据
x = torch.tensor(10.0)
y = torch.tensor([[3.0]])
print(x)
print(y)

tensor(10.)
tensor([[3.]])


In [4]:
# 初始化参数
w = torch.rand(1,1,requires_grad=True)
b = torch.rand(1,1,requires_grad=True)

In [5]:
# 前向传播，得到输出
z = w * x + b
print(z)

tensor([[2.2525]], grad_fn=<AddBackward0>)


In [6]:
print(x.is_leaf)
print(y.is_leaf)
print(w.is_leaf)
print(b.is_leaf)
print(z.is_leaf)

True
True
True
True
False


In [8]:
#设置损失函数
loss = torch.nn.MSELoss()
loss_value = loss(z,y)
print(loss_value)
print(loss_value.is_leaf)

tensor(0.5587, grad_fn=<MseLossBackward0>)
False


In [9]:
# 反向传播
loss_value.backward()

In [10]:
# 查看梯度
print(w.grad)
print(b.grad)

tensor([[-14.9491]])
tensor([[-1.4949]])
